[colors.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 8.0

[font.bold]
family = "B612 Mono"
style = "Bold"

[font.bold_italic]
family = "B612 Mono"
style = "Bold Italic"

[font.italic]
family = "B612 Mono"
style = "Italic"

[font.normal]
family = "B612 Mono"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[scrolling]
history = 100000
